version: '3.8'

services:

    mysql-app:
        build: ./db
        container_name: mysql-app    
        ports:
            - 3333:3306
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
            MYSQL_DATABASE: test
        networks:
            - app-network
        
    flask-app:
        build: ./app
        container_name: flask-app
        environment:
            MYSQL_HOST: mysql-app
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
            MYSQL_DATABASE: test 

        ports:
            - 5000:5000
        networks:
            - app-network
        depends_on:
            - mysql-app

networks:
    app-network:
        name: app-network
        driver: bridge
